#!/bin/python

import sys


def p1(i):
    def p(i):
        b = ["ab", "cd", "pq", "xy"]
        for s in b:
            if s in i:
                return False
        b = "aeiou"
        f = 0
        r = False
        p = ''
        for c in i:
            if p == c:
                r = True
            if c in b:
                f = f+1
            p = c
        if f < 3:
            return False
        return r
    c = 0
    for i in i:
        if p(i):
            c = c+1
    return c


def p2(i):
    def p(i):
        f = False
        for c in range(2, len(i)):
            f = f or i[c] == i[c-2]
        for s in range(1, len(i)):
            for j in range(s+2, len(i)):
                if i[j] == i[s] and i[j-1] == i[s-1]:
                    return f and True
        return False
    c = 0
    for i in i:
        if p(i):
            c = c+1
    return c


def p(i):
    print(p1(i))
    print(p2(i))


p(sys.stdin.read().split("\n"))
